version: '3.1'

services:
  # to build
  mongo:
    build: 4.0.7
    container_name: mongo_1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    command: mongod --bind_ip_all

  # use image
  mongo_built:
    image: my-registry:5000/dfw/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    command: mongod --bind_ip_all

  # registry instance to handle image
  registry:
    image: registry:2
    restart: always
    volumes:
      - registry:/var/lib/registry
    ports:
      - 5000:5000

  mongo-express:
    image:
volumes:
  registry: